name: toad-amazon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib<3.11
  - seaborn
  - xarray
  - netCDF4
  - h5py
  - jupyter
  - jupyterlab
  - ipykernel
  - geopandas
  - cartopy
  - rasterio
  - shapely
  - pyproj
  - gdal
  - cfgrib
  - pip
  - pip:
    - tipmip-toad==1.0.8
    - optuna
    - intake-esm
    - kerchunk
    - dask
    - plotly
    - pooch
    - regionmask
